module.exports = {
  ticketName: "ticket-",
  ticketDescription: "🌿 Ticket opened by",
  ticketCreate: "✅ Your ticket has been created",
  ticketAlreadyExist: "Sorry, but you already have an open ticket.",
  ticketNoPermissions: "Sorry, you don't have permission to do this.",
  ticketError: "Something went wrong, please try again later.",
  ticketMessageTitle: "Welcome, thank you for opening a ticket.",
  ticketMessageDescription:
    "A member of our moderation team will soon take care of your request. Thank you for patiently waiting with good humor.",
  ticketClose: "Close",
  ticketCloseEmoji: "📪",
  ticketLock: "Lock",
  ticketLockEmoji: "🔒",
  ticketUnlock: "Unlock",
  ticketUnlockEmoji: "🔓",
  ticketClaim: "Claim",
  ticketClaimEmoji: "👋",
  ticketManage: "Members",
  ticketManageEmoji: "➕",
  ticketManageMenuTitle: "Choose a member.",
  ticketManageMenuEmoji: "👤",
  ticketCloseTitle: "The ticket is currently being closed...",
  ticketCloseDescription: "The ticket will close in 5 seconds.",
  ticketSuccessLocked: "The ticket was successfully locked.",
  ticketAlreadyLocked: "This ticket is already locked.",
  ticketSuccessUnlocked: "The ticket was successfully unlocked.",
  ticketAlreadyUnlocked: "This ticket is already unlocked.",
  ticketSuccessClaim: "The ticket was successfully claimed by",
  ticketAlreadyClaim: "This ticket has already been claimed by",
  ticketDescriptionClaim: ", was claimed by",
  ticketTranscriptMember: "Member:",
  ticketTranscriptTicket: "Ticket:",
  ticketTranscriptClaimed: "Claimed:",
  ticketTranscriptModerator: "Moderator:",
  ticketTranscriptTime: "Time:",
  ticketMemberAdd: "has been added to the ticket.",
  ticketMemberRemove: "has been removed from the ticket.",
};
